name: flutterando_slidy_aula2
description: Usando Flutter junto com Slidy e Modular.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  flutter_mobx: ^1.0.1
  mobx: ^1.0.2+1
  flutter_modular: ^0.5.2
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.2
  build_runner: ^1.7.4
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs